### ISSUE TITLE
Multi-GPU with FFI

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/extension-ffi#12]
I have written a customized layer with FFI. It only works for a single GPU. For multi-gpu, it raise error during the backward. The cuda state is 'handled' by the FFI, will this be the problem?

**Comment by zhanghang1989** [comment]
```python
try:
with torch.cuda.device_of(input):
```
Fix this problem.

**Comment by D-X-Y** [comment]
Hi, would you mind to give a more detailed examples for how to solve this problem. I also meet the backward error with the FFI

**Comment by soumith** [comment]
@D-X-Y you can solve it by wrapping the code: `with torch.cuda.device_of(input):` whenever calling your FFI functions.

For example:

```python
with torch.cuda.device_of(input1):
   my_lib.my_lib_add_forward(input1, input2, output)
```

**Comment by D-X-Y** [comment]
Cool! Thanks a lot, this solved my problem!
