### ISSUE TITLE
"ImportError: undefined symbol: state"  --  since last upgrade

### ISSUE THREAD

**Issue by theevann** [pytorch/extension-ffi#14]
Hello !

I made a C extension for one of my code, but it doesn't work since I made the 0.2 upgrade.
So I tried the example of this repo again and I get the same error message:

    ImportError: .../extension-ffi/script/_ext/my_lib/_my_lib.so: undefined symbol: state

I do have CUDA on my machine.
I simply run `git clone`, then `python build.py` and `python test.py`. 

Is it on my side or something has to be changed in your code ?
I though it my be linked with the `extern THCState *state;` of my_lib_cuda.c

**Comment by soumith** [comment]
Hey @theevann . this is a bug I introduced in the latest binaries as of last night. I've made symbol exposure opt-out rather than opt-in, and I missed exposing `state`.
https://github.com/pytorch/pytorch/blob/v0.2.0/tools/pytorch.version

I'll fix this and generate new binaries today.

**Comment by theevann** [comment]
Great, thanks ! Looks like I was unlucky with the schedule :smile: 
Looking forward to it !

**Comment by soumith** [comment]
this should now be fixed with the latest binaries. thanks for waiting!

**Comment by Abbsalehi** [comment]
@soumith I have a same problem! could you please let me know how to fix it? 

_**Virtual Environment :**_ 
torch=0.4.1
gcc 5.4
cuda 9.0
python 3.6
